When parsing the event, also catch LinkageErrors
This so we can catch errors like NoClassDefFoundError. If we don't catch these, then the exception is just silently dropped.